# Change these first
owner: raulredes # Your GitHub organization or username, where this repository lives
repo: funsadu2026 # The name of this repository

sites:
  - name: Unanue
    url: http://unanue.funsadu.ar:60080
  - name: Cuchilloco
    url: http://cuchilloco.funsadu.ar:60080
  - name: Ceferino
    url: http://ceferino.funsadu.ar:60080
  - name: Aircontrol
    url: https://radios.funsadu.ar
    __dangerous__insecure: true
  - name: Gestion
    url: https://gestion.funsadu.ar/Radius/
 # - name: Auxiliar de Prueba

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: cname: estado2.funsadu.ar
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Estado
  introTitle: "**Estado** de los equipos "
  introMessage: Los equipos se monitorean cada 5 minutos, y se grafica el tiempo medio de respuesta
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
